# Generated by Django 5.2.5 on 2025-08-14 19:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Cantidad comprada (> 0)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-7'))])),
                ('price', models.DecimalField(decimal_places=4, help_text='Precio por unidad (> 0)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-7'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='average_price',
            field=models.DecimalField(decimal_places=4, help_text='Precio promedio debe ser > 0', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-7'))]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad debe ser > 0', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-7'))]),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['portfolio', 'symbol'], name='idx_asset_portfolio_symbol'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['added_at'], name='idx_asset_added_at'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['owner', 'name'], name='idx_portfolio_owner_name'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['created_at'], name='idx_portfolio_created_at'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('portfolio', 'symbol'), name='uniq_asset_portfolio_symbol'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_portfolio_owner_name'),
        ),
        migrations.AddField(
            model_name='assettransaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.asset'),
        ),
        migrations.AddIndex(
            model_name='assettransaction',
            index=models.Index(fields=['asset', 'created_at'], name='idx_transaction_asset_created'),
        ),
    ]
